apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw-core
  namespace: argocd
spec:
  project: openclaw-core
  destination:
    server: https://kubernetes.default.svc
    namespace: openclaw-system
  source:
    repoURL: https://github.com/9renpoto/homelabs.git
    targetRevision: main
    path: k8s/openclaw-core/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
