#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../.." && pwd)"
vars_file="${1:-${script_dir}/variables.pkrvars.hcl}"
output_dir="${2:-${repo_root}/.tmp}"
template_path="${script_dir}/ubuntu-openclaw.pkr.hcl"
user_data_path="${script_dir}/http/user-data"
windows_vars_file="${output_dir}/packer-windows.pkrvars.hcl"
windows_build_script="${output_dir}/packer-windows-build.ps1"

if [[ -z "${WSL_DISTRO_NAME:-}" ]]; then
  echo "This helper must run inside WSL so it can emit Windows-readable paths." >&2
  exit 1
fi

if ! command -v wslpath >/dev/null 2>&1; then
  echo "wslpath is required to render Windows-readable paths." >&2
  exit 1
fi

if [[ ! -f "${vars_file}" ]]; then
  echo "Variable file not found: ${vars_file}" >&2
  exit 1
fi

if [[ ! -f "${user_data_path}" ]]; then
  echo "Missing ${user_data_path}. Run infra/packer/render-user-data.sh first." >&2
  exit 1
fi

mkdir -p "${output_dir}"

declare -A vars=()
declare -a encountered_keys=()

while IFS= read -r line; do
  [[ "${line}" =~ ^[[:space:]]*$ ]] && continue
  [[ "${line}" =~ ^[[:space:]]*# ]] && continue
  [[ "${line}" =~ ^[[:space:]]*// ]] && continue

  if [[ "${line}" =~ ^[[:space:]]*([[:alnum:]_]+)[[:space:]]*=[[:space:]]*(.+)[[:space:]]*$ ]]; then
    key="${BASH_REMATCH[1]}"
    value="${BASH_REMATCH[2]}"
    vars["${key}"]="${value}"
    encountered_keys+=("${key}")
  fi
done < "${vars_file}"

if [[ -z "${vars[iso_url]:-}" ]]; then
  echo "iso_url must be set in ${vars_file}" >&2
  exit 1
fi

if [[ -z "${vars[iso_checksum]:-}" ]]; then
  echo "iso_checksum must be set in ${vars_file}" >&2
  exit 1
fi

if [[ -z "${vars[ssh_private_key_file]:-}" ]]; then
  echo "ssh_private_key_file must be set in ${vars_file}" >&2
  exit 1
fi

strip_quotes() {
  local value="$1"
  if [[ "${value}" =~ ^\"(.*)\"$ ]]; then
    printf '%s\n' "${BASH_REMATCH[1]}"
    return
  fi

  printf '%s\n' "${value}"
}

escape_hcl_string() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s\n' "${value}"
}

escape_powershell_string() {
  local value="$1"
  value="${value//\'/\'\'}"
  printf '%s\n' "${value}"
}

resolve_repo_relative_path() {
  local input_path="$1"

  if [[ "${input_path}" == /* ]]; then
    realpath -m "${input_path}"
    return
  fi

  realpath -m "${repo_root}/${input_path}"
}

rewrite_value_for_windows() {
  local key="$1"
  local raw_value="$2"
  local string_value
  local resolved_path

  case "${key}" in
    ssh_private_key_file)
      string_value="$(strip_quotes "${raw_value}")"
      resolved_path="$(resolve_repo_relative_path "${string_value}")"
      if [[ ! -f "${resolved_path}" ]]; then
        echo "ssh_private_key_file does not exist: ${resolved_path}" >&2
        exit 1
      fi
      printf '"%s"\n' "$(escape_hcl_string "$(wslpath -w "${resolved_path}")")"
      ;;
    iso_url)
      string_value="$(strip_quotes "${raw_value}")"
      if [[ "${string_value}" == *"://"* ]]; then
        printf '%s\n' "${raw_value}"
        return
      fi

      resolved_path="$(resolve_repo_relative_path "${string_value}")"
      if [[ ! -f "${resolved_path}" ]]; then
        echo "Local iso_url does not exist: ${resolved_path}" >&2
        exit 1
      fi
      printf '"%s"\n' "$(escape_hcl_string "$(wslpath -w "${resolved_path}")")"
      ;;
    output_directory)
      string_value="$(strip_quotes "${raw_value}")"
      if [[ "${string_value}" == /* ]]; then
        printf '"%s"\n' "$(escape_hcl_string "$(wslpath -w "${string_value}")")"
        return
      fi
      printf '%s\n' "${raw_value}"
      ;;
    *)
      printf '%s\n' "${raw_value}"
      ;;
  esac
}

ordered_keys=(
  vm_name
  iso_url
  iso_checksum
  output_directory
  headless
  cpus
  memory
  disk_size_mb
  network_adapter_type
  ssh_username
  ssh_private_key_file
)

declare -A emitted=()

{
  echo "# Generated by infra/packer/render-windows-packer-handoff.sh"
  echo "# Source: ${vars_file}"
  for key in "${ordered_keys[@]}"; do
    if [[ -n "${vars[${key}]:-}" ]]; then
      printf '%s = %s\n' "${key}" "$(rewrite_value_for_windows "${key}" "${vars[${key}]}")"
      emitted["${key}"]=1
    fi
  done

  for key in "${encountered_keys[@]}"; do
    if [[ -z "${emitted[${key}]:-}" ]]; then
      printf '%s = %s\n' "${key}" "$(rewrite_value_for_windows "${key}" "${vars[${key}]}")"
      emitted["${key}"]=1
    fi
  done
} > "${windows_vars_file}"

repo_root_windows="$(wslpath -w "${repo_root}")"
template_path_windows="$(wslpath -w "${template_path}")"
windows_vars_path_windows="$(wslpath -w "${windows_vars_file}")"
user_data_path_windows="$(wslpath -w "${user_data_path}")"

repo_root_windows_ps="$(escape_powershell_string "${repo_root_windows}")"
template_path_windows_ps="$(escape_powershell_string "${template_path_windows}")"
windows_vars_path_windows_ps="$(escape_powershell_string "${windows_vars_path_windows}")"
user_data_path_windows_ps="$(escape_powershell_string "${user_data_path_windows}")"

{
  printf '%s\n' "\$ErrorActionPreference = 'Stop'"
  printf '%s\n' "\$RepoRoot = '${repo_root_windows_ps}'"
  printf '%s\n' "\$TemplatePath = '${template_path_windows_ps}'"
  printf '%s\n' "\$VarsFilePath = '${windows_vars_path_windows_ps}'"
  printf '%s\n' "\$UserDataPath = '${user_data_path_windows_ps}'"
  printf '\n'
  printf '%s\n' "Write-Host \"RepoRoot     : \$RepoRoot\""
  printf '%s\n' "Write-Host \"TemplatePath : \$TemplatePath\""
  printf '%s\n' "Write-Host \"VarsFilePath : \$VarsFilePath\""
  printf '%s\n' "Write-Host \"UserDataPath : \$UserDataPath\""
  printf '\n'
  printf '%s\n' "Set-Location -LiteralPath \$RepoRoot"
  printf '%s\n' "& packer init \$TemplatePath"
  printf '%s\n' "& packer fmt -check (Join-Path \$RepoRoot \"infra\\packer\")"
  printf '%s\n' "& packer validate \"-var-file=\$VarsFilePath\" \$TemplatePath"
  printf '%s\n' "& packer build \"-var-file=\$VarsFilePath\" \$TemplatePath"
} > "${windows_build_script}"

echo "Rendered ${windows_vars_file}"
echo "Rendered ${windows_build_script}"
echo "Run on Windows PowerShell:"
echo "  powershell.exe -ExecutionPolicy Bypass -File \"$(wslpath -w "${windows_build_script}")\""
